image: golang:1.19

stages:
  - test
  - build
  
format:
  stage: test
  script:
    - go fmt $(go list ./...)
    - go vet $(go list ./...)
    - make test

compile:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - cmd