image: golang:1.18

format:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#    - if: $CI_PIPELINE_SOURCE == "push"
  stage: test
  script:
    - go fmt $(go list ./internal/...)
    - go vet $(go list ./internal/...)
    - make test

compile:
  stage: build
  script:
    - make build

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
