image: golang:1.18

format:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: test
  script:
    - go fmt $(go list ./internal/...)
    - go vet $(go list ./internal/...)
    - make test

compile:
  stage: build
  script:
    - make build

deploy:
  image: gitlab/gitlab-runner:latest
  stage: deploy
  script:
    - docker build -t cs_q_sim .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
    - docker push cs_q_sim
  only:
    - main