format:
  image: golang:1.18
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: test
  script:
    - go fmt $(go list ./internal/...)
    - go vet $(go list ./internal/...)
    - make test

compile:
  image: golang:1.18
  stage: build
  script:
    - make build

deploy:
  image: docker:latest
  stage: deploy
  script:
    - docker build -t cs_q_sim -f build/Dockerfile .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
    - docker push cs_q_sim
  only:
    - main