format:
  image: golang:1.18
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
  stage: test
  script:
    - go fmt $(go list ./internal/...)
    - go vet $(go list ./internal/...)
    - make test

compile:
  image: golang:1.18
  stage: build
  script:
    - make build
    - mv /cmd/qsim.out /artifacts/
  artifacts:
    paths:
      - qsim.out
  only: 
    - main

deploy:
  stage: deploy
  script:
    - git config --global user.email "jakub@korsak.xyz"
    - git config --global user.name "GitLab CI (JK)"
    - git tag $(date +'%Y%m%d%H%M%S')
    - git push --tags
  dependencies:
    - compile
  only:
    - main