physics:
  moleculemass: 1.0
  atommass: 2.0
  spin: 0.5
  spectrum:
    fieldrange: 100
    bathcount: 4
  timeevolution:
    magfield: 0.1
    timerange: 100
    initialket: uu
files:
  figdir: figures/
  outputsdir: outputs/
  results:
    cpu: "ryzen 5800x"
    ram: "32GB"