physics:
  bathdipolemoment: 1.0
  atomdipolemoment: 20.0
  spin: 0.5
  tiltangle: 0.785398163397
  geometry: ring
  bathcount: 
  spectrum:
    magneticfieldrange: 100
  timeevolution:
    bathmagneticfield: 1000.0
    centralmagneticfield: 1002.0
    timerange: 500
    dt: 1e-3
    initialket: duuuudddd
    observables:
      - operator: Sz
        slot: 0

files:
  figdir: figures/
  outputsdir: outputs/
  results:
    cpu: "Ryzen 5800x"
    ram: "32GB"
