simulation: spin-evolution
verbosity: debug
physics:
  bathdipolemoment: 1.0
  atomdipolemoment: 20.0
  spin: 0.5
  tiltangle: 0.0001
  constantdistance: 100
  geometry: sphere
  bathmagneticfield: 1000.0
  centralmagneticfield: 1002.0
  timerange: 400
  dt: 1e-4
  initialket: duuuudddd
  observables:
    - operator: Sz
      slot: 0

