physics:
  moleculemass: 1.0
  atommass: 2.0
  bathcount: 7
  spin: 0.5
  spectrum:
    fieldrange: 100
  timeevolution:
    magfield: 1e5
    timerange: 100
    initialket: dduuuuuu
files:
  figdir: figures/
  outputsdir: outputs/
  results:
    cpu: "i7-1185G7"
    ram: "32GB"