simulation: spin-evolution
verbosity: debug
physics:
  units: atomic
  bathdipolemoment: 1.77
  atomdipolemoment: 3626.87
  spin: 0.5
  tiltangle: 6.28318530718
  constantdistance: 1.5
  geometry: ring
  bathmagneticfield: 10000
  centralmagneticfield: 10010
  timerange: 500
  dt: 1e-6
  initialket: duuuudd
  observables:
    - operator: Sz
      slot: 0

