physics:
  moleculemass: 1.0
  atommass: 5.0
  bathcount: 6
  spin: 0.5
  spectrum:
    fieldrange: 100
  timeevolution:
    magfield: 1.0
    timerange: 10
    initialket:
      - 1
      - 0.0
files:
  figdir: figures/
  outputsdir: outputs/
  results:
    cpu: "i7-1185G7"
    ram: "32GB"