simulation: spin-evolution
verbosity: debug
physics:
  units: atomic
  bathdipolemoment: 1.77
  atomdipolemoment: 3626.87
  spin: 0.5
  tiltangle: 6.28318530718
  constantdistance: 1.5
  geometry: ring
  bathmagneticfield: 100
  centralmagneticfield: 101
  timerange: 1
  dt: 1e-7
  initialket: dupm
  observables:
    - operator: Sz
      slot: 0
