simulation: spin-evolution
verbosity: debug
physics:
  bathdipolemoment: 1
  atomdipolemoment: 20
  spin: 0.5
  tiltangle: 0.785398163397
  constantdistance: 1000
  geometry: ring
  bathmagneticfield: 1000
  centralmagneticfield: 1002
  timerange: 500
  dt: 0.001
  initialket: duuuudddd
  observables:
    - operator: Sz
      slot: 0
