physics:
  moleculemass: 1.0
  atommass: 20.0
  spin: 0.5
  tiltangle: 0.0
  spectrum:
    fieldrange: 100
    bathcount: 4
  timeevolution:
    magfield: 10000.0
    timerange: 500
    dt: 1e-3
    initialket: uuddddd
    observables:
      - operator: Sz
        slot: 1
      - operator: Sz
        slot: 4

files:
  figdir: figures/
  outputsdir: outputs/
  results:
    cpu: "i7-1185G7"
    ram: "32GB"