physics:
  bathdipolemoment: 1.0
  atomdipolemoment: 20.0
  spin: 0.5
  tiltangle: 0.785398163397
  spectrum:
    magneticfieldrange: 100
    bathcount: 4
  timeevolution:
    bathmagneticfield: 1000.0
    centralmagneticfield: 1002.0
    timerange: 500
    dt: 1e-3
    initialket: uuddddd
    observables:
      - operator: Sz
        slot: 1
      - operator: Sz
        slot: 2
      - operator: Sz
        slot: 3
      - operator: Sz
        slot: 4

files:
  figdir: figures/
  outputsdir: outputs/
  results:
    cpu: "i7-1185G7"
    ram: "32GB"