simulation: spin-evolution
verbosity: debug
files:
  diagonalizationdir:
    outputs/diag-2023-06-25T22:08:52+02:00
physics:
  tiltangle: 0.03
  constantdistance: 1.5
  geometry: ring
  timerange: 500
  dt: 1e-6
  initialket: duuuuuudddddd
  observables:
    - operator: Sz
      slot: 0
