simulation: spin-evolution
verbosity: debug
physics:
  units: atomic
  bathdipolemoment: 1.77
  atomdipolemoment: 3626.87
  spin: 0.5
  constantdistance: 1.5
  geometry: icosahedron
  bathmagneticfield: 10000
  centralmagneticfield: 10100
  timerange: 500
  dt: 1e-6
  initialket: duuuuuudddddd
  observables:
    - operator: Sz
      slot: 0
