simulation: interactions
verbosity: debug
physics:
  bathdipolemoment: 1.0
  atomdipolemoment: 20.0
  spin: 0.5
  tiltangle: 0.7
  geometry: ring
  bathmagneticfield: 1000.0
  centralmagneticfield: 1002.0

