simulation: spin-evolution-selected-coeffs
verbosity: debug
physics:
  spin: 0.5
  timerange: 500
  dt: 6.283e-7
  model: XX
  initialket: dudududududud
  observables:
    - operator: Sz
      slot: 0
