name: Build, test and run

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yalm'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make build
    - name: Test
      run: make test

