name: Build and test

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yalm'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make build
    - name: Test
      run: make test

